return {		--[[ 01_types_and_scopes.xlsx -> Item ]]
[1] = {
	id = 1,
	name = [[Long Sword]],
	desc = [[A plain long sword]],
	weight = 100,
	price = 10,
	icon = [[icon_1001]],
	extra = nil,
	on_sale = true,
},
[2] = {
	id = 2,
	name = [[Iron Shield]],
	desc = [[A sturdy iron shield]],
	weight = 80,
	price = 50,
	icon = [[icon_1002]],
	extra = 100+50,
	on_sale = false,
},
[3] = {
	id = 3,
	name = [[Potion]],
	weight = 200,
	price = 5,
	icon = [[icon_1003]],
	extra = nil,
	on_sale = true,
},
[4] = {
	id = 4,
	name = [[Scroll]],
	desc = [[Teleports you to a random place]],
	weight = 50,
	icon = [[icon_1004]],
	extra = {quality=3},
	on_sale = true,
},
}