return {		--[[ 01_types_and_scopes.xlsx -> Item ]]
[1] = {
	id = 1,
	name = [[长剑]],
	desc = [[一把普通的长剑]],
	weight = 100,
	price = 10,
	icon = [[icon_1001]],
	extra = nil,
	on_sale = true,
},
[2] = {
	id = 2,
	name = [[铁盾]],
	desc = [[结实的铁盾]],
	weight = 80,
	price = 50,
	icon = [[icon_1002]],
	extra = 100+50,
	on_sale = false,
},
[3] = {
	id = 3,
	name = [[药水]],
	weight = 200,
	price = 5,
	icon = [[icon_1003]],
	extra = nil,
	on_sale = true,
},
[4] = {
	id = 4,
	name = [[卷轴]],
	desc = [[使用后随机传送]],
	weight = 50,
	icon = [[icon_1004]],
	extra = {quality=3},
	on_sale = true,
},
}